name: CD - Promoción y Despliegue de Modelo
on:
  workflow_run:
    # Asegúrar que este nombre coincida EXACTAMENTE con el 'name' de ci.yml
    workflows: ["CI - Entrenamiento y Validación de Modelo"] 
    types: [completed]
    branches: [main]
jobs:
  deploy-model:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mlflow-deploy

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Descargar artefactos del run anterior
        uses: actions/download-artifact@v4
        with:
          # 🛑 Debe coincidir con el nombre usado en el CI.
          name: mlruns-ci-results 
          # La descarga se hará en mlflow-deploy/, lo que recrea mlflow-deploy/mlruns/
          path: mlflow-deploy/


      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Instalar dependencias
        run:  pip install -r requirements.txt
      
      - name: Promocionar modelo (simulado)
        run: |
          echo "✅ Promoción del modelo validado a producción"
          # Aquí puedes agregar comandos para actualizar el estado del modelo en MLflow Registry
          # o desplegarlo usando mlflow models serve
